name: LEMP Server
on:
  push:
    branches:
    - main
jobs:
  Docker-LEMP:
    runs-on: self-hosted
    env:
      BUILD_NUMBER: ${{ github.run_number }}
    steps:
      - uses: actions/checkout@v3
      - name: Install Docker Compose on self devopsmolvi-runner
        run: |
            mkdir -p ~/.docker/cli-plugins/
            curl -SL https://github.com/docker/compose/releases/latest/download/docker-compose-linux-x86_64 -o ~/.docker/cli-plugins/docker-compose
            chmod +x ~/.docker/cli-plugins/docker-compose
            docker compose version
        
      - name: Logging into the Docker Hub
        uses: docker/login-action@v1
        with:
           username: ${{ secrets.DOCKER_USER }}
           password: ${{ secrets.DOCKER_PASS }}

      - name: Build Docker Images with their respective tags
        run: docker compose build
          
      - name: Push Docker images to Docker Hub
        run: docker compose push   
